### ISSUE TITLE
Ability to mock several APIs

### ISSUE THREAD

**Issue by devorbitus** [seriema/angular-apimock#18]
Thanks for this, I really do love what it does!

I have forked the repo to perhaps work on this but we have a need for the library to be able to mock out several APIs instead of just one.

**Comment by seriema** [comment]
I wish Github would email me when someone writes on my repo's =)

Glad you like it! I checked out your fork. There wasn't anything added that I could see?

When you say mock several API's, do you mean different URL's that don't start the same? Like `//external.com/api` and `/api` etc? Would you want it to behave the same otherwise, like just translating those URL's to local file paths? Feel free to write a mock sample here in the comments so I understand how you'd like to use it. =)

**Comment by seriema** [comment]
@devorbitus if you have any thoughts on how you would like this to work then let me know and I'll re-open this issue. For now I'll close it.

**Comment by Wolfium** [comment]
Exactly as you said, I have diferents endpoints api with different URLs using CORS.
May be just an array of strings handled for API URLs?

Thanks again for great library.

**Comment by seriema** [comment]
@Wolfium Thanks for doing #29 !
