### ISSUE TITLE
bug or enhancement

### ISSUE THREAD

**Issue by gamedevhelper** [seriema/angular-apimock#28]
I am unable to get this API to work for more than 1 request.  Will the config below with multiple routes  work?

    .config(function (apiMockProvider) {
      apiMockProvider.config({
          mockDataPath: '/my_mock_data_path1',
          apiPath: '/my_api_path1',
          apiMock: 'true'
        },
        {
          mockDataPath: '/my_mock_data_path2',
          apiPath: '/my_api_path2',
          apiMock: 'true'
        },
        {
          mockDataPath: '/my_mock_data_path3',
          apiPath: '/my_api_path3',
          apiMock: 'true'
        });
    })

(I would love to be able to chain my all mock route in the config and also able to set all my flags in config.)

**Comment by seriema** [comment]
It's only the base path that's configurable as it's meant to be simple and fast to mock, as well as have actual files representing/documenting the API. So it only handles one. If you have a good use case for API's that have multiple root levels I might consider adding this.

Oh, you don't need the `apiMock` boolean. You only need to use it on specific `$http` calls or add it in the browsers URL. Let me know how the docs could be improved if this was unclear.

**Comment by seriema** [comment]
If I was unclear (I'm travelling on vacation atm) then the only thing you need to do for multiple requests is match your base root path to a folder. The rest will be the same. I.e. set `apiPath: '/api'` and `mockDataPath: '/mocked'` then any request to `/api/...` will be redirected to `/mocked/...`. For example `/api/products/5` will go to `mocked/products/5`.

What isn't supported is the "typical mocking library config" like `$http` uses where you manually have to route every request yourself. The reason is to keep it simple and easily switch between the real API and mocked data, regardless of your browser or environment.

**Comment by gamedevhelper** [comment]
Excellent this is exactly the library I needed.  I miss understood the usage.

I wanted to control my app during 'boot/startup' (with a config file) either to always call mock data or hit the real API.  Here is how I accomplished it.  This is just quickly written sample code. 

//my config file myconfig.json
{
  "mode" : "false",
  "api-url" :"http://localhost:8080/myapi/rs",
  "mock-url" : "/data"
}


//my app.js file
angular
  .module('myApp', [
    'apiMock'
  ])
  .constant('MY_CONSTANT', {
    'CONFIG': {'APIMOCK': 'false'}
  })
  .config(function (apiMockProvider, MY_CONSTANT) {
    var initInjector = angular.injector(['ng']);
    var $http = initInjector.get('$http');

    //first read the config file
    $http({method: 'GET', url: '/conf/myconf.json', 'apiMock': false})
      .then(function (response) {
        var mockConfig = {};

        //save it in an hashmap to make it easy to look up
        angular.forEach(response.data, function (value, key) {
          mockConfig[key] = value;
        });

        //save it in constant so it can be used throughout the app
        MY_CONSTANT.CONFIG.APIMOCK = angular.lowercase(mockConfig['mode']);
        if (!mockConfig['api-url']) {//if api-url element is missing in config file
          MY_CONSTANT.CONFIG.APIMOCK = 'false';
        } else {
          apiMockProvider.config({
            mockDataPath: mockConfig['mock-url'],
            apiPath: mockConfig['api-url']
          });
        }
      }, function () {//failed to get the config file
        MY_CONSTANT.CONFIG.APIMOCK = 'false';//not need but good practice
      });
  }//end of angular.module('myApp'
);

//in all my other code wherever I call $http I just do
angular
  .module('myApp', [
    'apiMock'
  ])
  .controller('MyCtrol', function ($scope, $http) {

    $http({method: 'GET', url: 'http://localhost:4030/rs/cust', 'apiMock': MY_CONSTANT.CONFIG.APIMOCK})
      .then(function (response) {
        $scope.mydata = response.data;
      });
  });

**Comment by seriema** [comment]
Ah, I see. I'm planning something like that for the feature request in #24. I'm travelling for another week though so PR's are welcome.

Btw, boolean values should be without quotes (in your constants etc). The `forEach` for the "hashmap" isn't needed I think, because JavaScript objects are already like that. I think other parts could be simplified too but I'm reading/answering on my phone atm. ^^
