### ISSUE TITLE
Install through NPM error

### ISSUE THREAD

**Issue by Elecash** [seriema/angular-apimock#60]
I've tried to install through NPM and I'm getting this error:

	ENOENT No bower.json present
	npm WARN EPACKAGEJSON safx-web@1.0.0 No repository field.
	npm WARN EPACKAGEJSON safx-web@1.0.0 No license field.
	npm ERR! Darwin 14.3.0
	npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "angular-apimock" "--save-dev"
	npm ERR! node v4.2.2
	npm ERR! npm  v3.3.9
	npm ERR! code ELIFECYCLE

	npm ERR! angular-apimock@0.3.2 postinstall: `bower install`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the angular-apimock@0.3.2 postinstall script 'bower install'.
	npm ERR! This is most likely a problem with the angular-apimock package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     bower install
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls angular-apimock
	npm ERR! There is likely additional logging output above.

It works as expected with Bower.

**Comment by seriema** [comment]
Thank you for reminding me. It was actually fixed in https://github.com/seriema/angular-apimock/commit/a696e14d4d6ef1175c38c5c3bc6d63358968b0e2 when I removed the postinstall step that used Bower since it wasn't needed. But it wasn't published, until now. `v0.3.3` is up and I tested it with `npm v2` and `v3`, and it worked for me. Let me know how it works for you as well.

**Comment by Elecash** [comment]
Yes, it works, thank you :)
